### ISSUE TITLE
qProfiler User Manual Availability

### ISSUE THREAD

**Issue by DarioS** [AdamaJava/adamajava#199]
The performance of qProfiler for predicting telomere length in cancer samples was highly recommended by a colleague. Therefore, I would like to try it on my own data set but I found there is no user manual for it. Does it handle differences in tumour purity between samples? For example one sample might have 25% tumour purity and another might have 70% purity, as estimated by PURPLE.

**Comment by grendeloz** [comment]
Hi Dario, qProfiler is not the tool you want - it creates summary metrics for quality assessment of BAM and FASTQ files.  For telomere quantification, qMotif is the tool you want. It is a motif-finding tool so it does not account for purity or any other biological factors - it searches reads in BAM files for specified motifs. It was originally designed to find telomere motifs so it has some features customised to that use case.  For example, it has a 2-stage matching strategy so it can do a quick exact-string first stage match and then do a slow regex-based second stage match only on reads that passed the first stage. It can also be constrained so that it only looks at particular genomic regions (INCLUDES) or it can skip particular genomic regions (EXCLUDES). It returns counts of telomeric motifs and can also output a BAM file that contains any reads with telomeric reads so you can do your own more sophisticated downstream analyses.

See the documentation at https://adamajava.readthedocs.io/en/latest/qmotif/qmotif_1_2/ which includes an example configuration file designed for fast telomere hunting.
