### ISSUE TITLE
CreateQsnpIni failing in 6.b3dea13.11476

### ISSUE THREAD

**Issue by shimbalama** [AdamaJava/adamajava#56]
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/scratch/pbs.7074336.hpcpbs02
Error: Could not find or load main class CreateQsnpIni
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/scratch/pbs.7074336.hpcpbs02
Exception in thread "main" org.qcmg.snp.SnpException: Cannot read input file qsnp.0dee0f1a-c97d-4610-8afe-e621e22d4b69.ini
        at org.qcmg.snp.Main.setup(Main.java:65)
        at org.qcmg.snp.Main.main(Main.java:45)

from /working/genomeinfo/cromwell-test/cromwell-executions/somaticDnaARGSToMaf/a1248dcf-7778-417c-914a-be5d08e01142/call-stdQsnp/execution

**Comment by delocalizer** [comment]
I believe what's happened here is that because of the changes to the java and scala codebases, the code on avalon has got ahead of the WDL workflow and the WDL dependencies files originally generated to run the job, and the latter are now stale. They refer to an old jar (core-assembly-1.0.jar) that had been removed at the time this job ran. Turns out that wasn't a great idea since folks are actually still using it :blush: — so I've restored it and if anyone still has old workflows lying around that refer to that they will now run, but my best advice would be to regenerate the WDL and dependencies zip, and try again.

**Comment by delocalizer** [comment]
I renamed this issue since the original title was a bit of a red herring — the WDL task in the problematic workflow isn't actually using qsnp jar to generate the ini file; it's using the old `core-tools` jar. `CreateQsnpIni` works fine in qsnp 6.b3dea13.11476, as nightly regression test shows.
